dotfiles_dir = "Projects/raja-config/"

[settings]
prehooks = [ "bash ./scripts/install_binaries.sh" ]
posthooks = [ "sway reload 2>/dev/null" ]

[settings.dots]
alacritty  = { source = "configs/alacritty",target = ".config/alacritty" }
kanshi     = { source = "configs/kanshi",  target = ".config/kanshi" }
nvim       = { source = "configs/nvim/",   target = ".config/nvim" }
rofi       = { source = "configs/rofi",    target = ".config/rofi" }
sway       = { source = "configs/sway",    target = ".config/sway" }
swaylock   = { source = "configs/swaylock",target = ".config/swaylock" }
waybar     = { source = "configs/waybar",  target = ".config/waybar", direct=true }
zsh        = { source = "configs/zsh/zshrc", target = ".config/zsh/.zshrc" }
